# Generated by Django 5.1.6 on 2025-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workinghours',
            name='unique_shift_per_day',
        ),
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together={('employee', 'weekday')},
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='shift_type',
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_shift_per_day'),
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='shift_type',
        ),
    ]
