# Generated by Django 5.1.6 on 2025-03-09 17:04

import wfm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(upload_to=wfm.models.UserDocument.get_upload_path),
        ),
    ]
