# Generated by Django 5.1.6 on 2025-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0002_alter_userdocument_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapistbooking',
            old_name='payment_date',
            new_name='extra_hours_payment_date',
        ),
        migrations.AddField(
            model_name='therapistbooking',
            name='extra_hours_payment_status',
            field=models.CharField(choices=[('PENDING', 'Ausstehend'), ('PAID', 'Bezahlt')], default='PENDING', help_text='Zahlungsstatus nur für die Mehrstunden', max_length=10, verbose_name='Zahlungsstatus Mehrstunden'),
        ),
        migrations.AlterField(
            model_name='timecompensation',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Wird automatisch aus dem Arbeitsplan berechnet', max_digits=4, verbose_name='Stunden'),
        ),
    ]
