# Generated by Django 5.1.6 on 2025-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0002_remove_workinghours_unique_shift_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistbooking',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tatsächlich verwendete Stunden'),
        ),
    ]
