# Generated by Django 5.1.6 on 2025-03-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0003_rename_payment_date_therapistbooking_extra_hours_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistbooking',
            name='payment_status',
        ),
    ]
