# Generated by Django 5.1.6 on 2025-02-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0003_therapistbooking_actual_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], verbose_name='Wochentag')),
                ('start_time', models.TimeField(verbose_name='Beginn')),
                ('end_time', models.TimeField(verbose_name='Ende')),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'THERAPIST'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Therapeut/in')),
            ],
            options={
                'verbose_name': 'Raumbuchungs-Vorlage',
                'verbose_name_plural': 'Raumbuchungs-Vorlagen',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('therapist', 'weekday')},
            },
        ),
    ]
