# Generated by Django 5.1.6 on 2025-03-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0005_scheduletemplate_break_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimeaccount',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Überstundenkonto', 'verbose_name_plural': 'Überstundenkonten'},
        ),
        migrations.AlterModelOptions(
            name='sickleave',
            options={'ordering': ['-start_date'], 'verbose_name': 'Krankenstand', 'verbose_name_plural': 'Krankenstände'},
        ),
        migrations.AlterModelOptions(
            name='therapistbooking',
            options={'ordering': ['-date'], 'verbose_name': 'Therapeutenbuchung', 'verbose_name_plural': 'Therapeutenbuchungen'},
        ),
        migrations.AlterModelOptions(
            name='therapistscheduletemplate',
            options={'ordering': ['-valid_from', 'weekday', 'start_time'], 'verbose_name': 'Therapeuten-Stundenvorlage', 'verbose_name_plural': 'Therapeuten-Stundenvorlagen'},
        ),
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-start_date'], 'verbose_name': 'Urlaub', 'verbose_name_plural': 'Urlaube'},
        ),
        migrations.AlterModelOptions(
            name='vacationentitlement',
            options={'ordering': ['-year'], 'verbose_name': 'Urlaubsanspruch', 'verbose_name_plural': 'Urlaubsansprüche'},
        ),
        migrations.RenameField(
            model_name='overtimeaccount',
            old_name='is_finalized',
            new_name='overtime_paid',
        ),
        migrations.RenameField(
            model_name='overtimeaccount',
            old_name='finalized_at',
            new_name='overtime_paid_date',
        ),
        migrations.RenameField(
            model_name='therapistbooking',
            old_name='extra_hours_payment_date',
            new_name='therapist_extra_hours_payment_date',
        ),
        migrations.RenameField(
            model_name='therapistbooking',
            old_name='extra_hours_payment_status',
            new_name='therapist_extra_hours_payment_status',
        ),
    ]
