# Generated by Django 5.1.6 on 2025-03-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0006_alter_overtimeaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeaccount',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimeaccount',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
