# Generated by Django 5.1.6 on 2025-02-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0006_alter_therapistbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.CharField(default='#3498DB', help_text='Farbe für die Anzeige in Kalendern und Listen', max_length=7, verbose_name='Anzeigefarbe'),
        ),
    ]
