# Generated by Django 5.1.6 on 2025-03-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0007_overtimeaccount_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Originaldatei'),
        ),
    ]
