# Generated by Django 5.1.6 on 2025-02-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0008_alter_therapistbooking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Ordinationsinhaber/in'), ('ASSISTANT', 'Ordinationsassistenz'), ('CLEANING', 'Reinigungsdienst'), ('THERAPIST', 'Therapeut/in')], default='ASSISTANT', max_length=10),
        ),
    ]
