# Generated by Django 5.1.6 on 2025-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0008_userdocument_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
