# Generated by Django 5.1.6 on 2025-02-16 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0009_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickleave',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sickleave',
            name='document_provided',
        ),
        migrations.AddField(
            model_name='sickleave',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Krankmeldung vorgelegt'), ('PENDING', 'Keine Krankmeldung')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='start_date',
            field=models.DateField(),
        ),
    ]
