# Generated by Django 5.1.6 on 2025-03-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0009_workinghours_is_paid_workinghours_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleave',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_leave', to='wfm.userdocument'),
        ),
    ]
