# Generated by Django 5.1.6 on 2025-02-16 17:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0010_remove_sickleave_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'ordering': ['-valid_from', 'weekday'], 'verbose_name': 'Arbeitszeit-Vorlage', 'verbose_name_plural': 'Arbeitszeit-Vorlagen'},
        ),
        migrations.AlterModelOptions(
            name='therapistscheduletemplate',
            options={'ordering': ['-valid_from', 'weekday', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='valid_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Gültig ab'),
        ),
        migrations.AddField(
            model_name='therapistscheduletemplate',
            name='valid_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Gültig ab'),
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/', verbose_name='Datei')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzerdokument',
                'verbose_name_plural': 'Benutzerdokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
