# Generated by Django 5.1.6 on 2025-03-16 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0010_sickleave_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='weekly_target_hours',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Vereinbarte wöchentliche Arbeitsstunden', max_digits=4, verbose_name='Wöchentliche Sollstunden'),
        ),
        migrations.AlterField(
            model_name='overtimeaccount',
            name='total_overtime',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positiv = Überstunden, Negativ = Unterstunden', max_digits=5),
        ),
        migrations.CreateModel(
            name='AveragingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_hours', models.DecimalField(decimal_places=2, help_text='Ziel-Arbeitsstunden für den gesamten Durchrechnungszeitraum', max_digits=5)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tatsächlich geleistete Stunden im Durchrechnungszeitraum', max_digits=5, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Kennzeichnet, ob der Durchrechnungszeitraum abgeschlossen ist')),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Durchrechnungszeitraum',
                'verbose_name_plural': 'Durchrechnungszeiträume',
                'ordering': ['-start_date'],
            },
        ),
    ]
