# Generated by Django 5.1.6 on 2025-03-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0010_sickleave_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimeaccount',
            name='finalized_at',
        ),
        migrations.RemoveField(
            model_name='overtimeaccount',
            name='hours_for_timecomp',
        ),
        migrations.RemoveField(
            model_name='overtimeaccount',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='overtimeaccount',
            name='total_overtime',
        ),
        migrations.AddField(
            model_name='overtimeaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive Werte = Überstunden, Negative = Minderstunden', max_digits=6),
        ),
    ]
