# Generated by Django 5.1.6 on 2025-02-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0011_alter_scheduletemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Arbeitszeit', 'verbose_name_plural': 'Arbeitszeiten'},
        ),
        migrations.RemoveConstraint(
            model_name='workinghours',
            name='unique_shift_per_day',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='sick_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='wfm.sickleave'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='time_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='wfm.timecompensation'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='vacation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='wfm.vacation'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='break_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('employee', 'date')},
        ),
    ]
