# Generated by Django 5.1.6 on 2025-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0011_remove_overtimeaccount_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeaccount',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimeaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive Werte = Überstunden, Negative = Minderstunden', max_digits=8),
        ),
    ]
