# Generated by Django 5.1.6 on 2025-03-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0011_customuser_weekly_target_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averagingperiod',
            options={},
        ),
        migrations.RemoveField(
            model_name='averagingperiod',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='averagingperiod',
            name='target_hours',
        ),
        migrations.AddField(
            model_name='averagingperiod',
            name='weeks',
            field=models.IntegerField(default=13, help_text='Anzahl der Wochen im Durchrechnungszeitraum'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_hours_per_week',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Vereinbarte wöchentliche Arbeitsstunden', max_digits=4, verbose_name='Wöchentliche Sollstunden'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Ordinationsinhaber/in'), ('ASSISTANT', 'Ordinationsassistenz'), ('CLEANING', 'Reinigungsdienst'), ('THERAPIST', 'Therapeut/in')], max_length=10),
        ),
    ]
