# Generated by Django 5.1.6 on 2025-03-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0012_alter_averagingperiod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='weekly_target_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=40.0, help_text='Vereinbarte wöchentliche Arbeitsstunden', max_digits=4, null=True, verbose_name='Wöchentliche Sollstunden'),
        ),
    ]
