# Generated by Django 5.1.6 on 2025-02-22 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0012_alter_workinghours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='timecompensation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timecompensation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='timecompensation',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Standardmäßig 8 Stunden für einen vollen Arbeitstag', max_digits=4, verbose_name='Stunden'),
        ),
        migrations.AlterField(
            model_name='timecompensation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Anmerkungen'),
        ),
        migrations.AlterField(
            model_name='timecompensation',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Angefragt'), ('APPROVED', 'Genehmigt'), ('REJECTED', 'Abgelehnt')], default='REQUESTED', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='OvertimeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_overtime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hours_for_payment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hours_for_timecomp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
