# Generated by Django 5.1.6 on 2025-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0012_overtimeaccount_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Berechnete Urlaubsstunden', max_digits=5),
        ),
    ]
