# Generated by Django 5.1.6 on 2025-03-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0013_vacation_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='soll_end',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='soll_hours',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='soll_start',
        ),
    ]
