# Generated by Django 5.1.6 on 2025-03-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0013_alter_customuser_weekly_target_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='weekly_target_hours',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='working_hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, default=40.0, help_text='Vereinbarte wöchentliche Arbeitsstunden', max_digits=4, null=True, verbose_name='Wöchentliche Sollstunden'),
        ),
    ]
