# Generated by Django 5.1.6 on 2025-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0013_alter_vacation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='soll_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='soll_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
