# Generated by Django 5.1.6 on 2025-03-17 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0014_remove_customuser_weekly_target_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averagingperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'Durchrechnungszeitraum', 'verbose_name_plural': 'Durchrechnungszeiträume'},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='averagingperiod',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ASSISTANT', 'CLEANING']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
