# Generated by Django 5.1.6 on 2025-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0014_workinghours_soll_end_workinghours_soll_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='ist_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='soll_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
