# Generated by Django 5.1.6 on 2025-03-26 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0014_remove_workinghours_soll_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimeaccount',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='overtimeaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='overtimeaccount',
            name='payment_locked_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimeaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Positive Werte = Überstunden, Negative = Minderstunden', max_digits=8),
        ),
        migrations.AlterField(
            model_name='overtimeaccount',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OvertimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfm.workinghours')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
