# Generated by Django 5.1.6 on 2025-02-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0015_workinghours_ist_hours_workinghours_soll_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('type', models.CharField(choices=[('HOLIDAY', 'Gesetzlicher Feiertag'), ('VACATION', 'Ordinationsurlaub'), ('TRAINING', 'Fortbildung'), ('OTHER', 'Sonstiges')], default='OTHER', max_length=20, verbose_name='Art der Schließung')),
                ('is_recurring', models.BooleanField(default=False, help_text='Gilt für gesetzliche Feiertage', verbose_name='Jährlich wiederkehrend')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schließtag',
                'verbose_name_plural': 'Schließtage',
                'ordering': ['date'],
                'unique_together': {('date', 'type')},
            },
        ),
    ]
