# Generated by Django 5.1.6 on 2025-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0015_alter_averagingperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Stunden'),
        ),
    ]
