# Generated by Django 5.1.6 on 2025-03-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0016_alter_overtimeaccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeentry',
            name='working_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wfm.workinghours'),
        ),
    ]
