# Generated by Django 5.1.6 on 2025-02-24 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0017_alter_vacation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['-date'], 'verbose_name': 'Arbeitszeit', 'verbose_name_plural': 'Arbeitszeiten'},
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Pausendauer'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(verbose_name='Ist-Ende'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='soll_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Soll-Ende'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='soll_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Soll-Start'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(verbose_name='Ist-Start'),
        ),
    ]
