# Generated by Django 5.1.6 on 2025-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0017_alter_overtimeentry_working_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimeaccount',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Überstundenkonto', 'verbose_name_plural': 'Überstundenkonten'},
        ),
        migrations.AlterModelOptions(
            name='overtimeentry',
            options={'ordering': ['-date'], 'verbose_name': 'Überstundeneintrag', 'verbose_name_plural': 'Überstundeneinträge'},
        ),
        migrations.AlterField(
            model_name='overtimeentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='Positive Werte = Überstunden, Negative = Minderstunden', max_digits=5),
        ),
        migrations.AlterField(
            model_name='overtimeentry',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Gesperrt wenn zur Auszahlung markiert'),
        ),
    ]
