# Generated by Django 5.1.6 on 2025-03-29 16:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0018_alter_overtimeaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('wage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_wages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
