# Generated by Django 5.1.6 on 2025-02-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0018_alter_workinghours_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='ist_hours',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='sick_leave',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='soll_end',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='soll_hours',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='soll_start',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='time_comp',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='vacation',
        ),
    ]
