# Generated by Django 5.1.6 on 2025-02-24 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0019_remove_workinghours_ist_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Arbeitszeit', 'verbose_name_plural': 'Arbeitszeiten'},
        ),
        migrations.AddField(
            model_name='workinghours',
            name='ist_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='sick_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='wfm.sickleave'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='soll_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='soll_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='soll_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='time_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='wfm.timecompensation'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='vacation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to='wfm.vacation'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='break_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
