# Generated by Django 5.1.6 on 2025-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0020_alter_monthlywage_options_monthlywage_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistbooking',
            name='therapist_extra_hours_payment_date',
        ),
        migrations.RemoveField(
            model_name='therapistbooking',
            name='therapist_extra_hours_payment_status',
        ),
        migrations.AddField(
            model_name='therapistbooking',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Gibt an, ob die Mehrstunden bezahlt wurden', verbose_name='Bezahlt'),
        ),
        migrations.AddField(
            model_name='therapistbooking',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Datum der Bezahlung der Mehrstunden', null=True, verbose_name='Bezahlt am'),
        ),
    ]
