# Generated by Django 5.1.6 on 2025-04-01 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0021_remove_therapistbooking_therapist_extra_hours_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Stunden')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Berechneter Auszahlungsbetrag', max_digits=10, verbose_name='Betrag')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Bezahlt')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Bezahlt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Überstunden-Auszahlung',
                'verbose_name_plural': 'Überstunden-Auszahlungen',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
