# Generated by Django 5.1.6 on 2025-03-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0021_alter_userdocument_options_remove_userdocument_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='original_filename',
        ),
    ]
