# Generated by Django 5.1.6 on 2025-03-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0023_customuser_city_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistbooking',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bezahlt am'),
        ),
        migrations.AddField(
            model_name='therapistbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Ausstehend'), ('PAID', 'Bezahlt')], default='PENDING', max_length=10, verbose_name='Zahlungsstatus'),
        ),
    ]
