# Generated by Django 5.1.6 on 2025-04-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0024_alter_overtimepayment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimepayment',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bezahlt am'),
        ),
    ]
