# Generated by Django 5.1.6 on 2025-03-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0024_therapistbooking_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapistscheduletemplate',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.AddField(
            model_name='therapistscheduletemplate',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
