# Generated by Django 5.1.6 on 2025-04-02 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0025_alter_overtimepayment_paid_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtimeaccount',
            unique_together={('employee', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='overtimeaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='overtimeaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aktuelle Gesamtbilanz inklusive aller Änderungen', max_digits=8),
        ),
        migrations.AddField(
            model_name='overtimeaccount',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='overtimeaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.RemoveField(
            model_name='overtimeaccount',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='overtimeaccount',
            name='overtime_paid',
        ),
        migrations.RemoveField(
            model_name='overtimeaccount',
            name='overtime_paid_date',
        ),
    ]
