# Generated by Django 5.1.6 on 2025-03-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0025_alter_therapistscheduletemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistscheduletemplate',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
