# Generated by Django 5.1.6 on 2025-03-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0026_therapistscheduletemplate_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistscheduletemplate',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
