# Generated by Django 5.1.6 on 2025-03-08 08:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0027_alter_therapistscheduletemplate_actual_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistscheduletemplate',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Stunden'),
        ),
    ]
