# Generated by Django 5.1.6 on 2025-04-07 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0027_delete_monthlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlywage',
            name='difference_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlywage',
            name='total_scheduled_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
