# Generated by Django 5.1.6 on 2025-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0028_alter_therapistscheduletemplate_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistscheduletemplate',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, verbose_name='Stunden'),
        ),
    ]
