# Generated by Django 5.1.6 on 2025-03-08 08:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0029_alter_therapistscheduletemplate_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapistscheduletemplate',
            options={'ordering': ['-valid_from', 'weekday', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='therapistscheduletemplate',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='therapistscheduletemplate',
            name='notes',
        ),
        migrations.AlterField(
            model_name='therapistscheduletemplate',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
    ]
