# Generated by Django 5.1.6 on 2025-03-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0030_alter_therapistscheduletemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistbooking',
            name='status',
        ),
    ]
